[package]
name = "ql-grep"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1"
clap = { version = "^4.0", features = ["derive"] }
crossbeam-channel = "^0.5"
env_logger = "^0.9"
ignore = "^0.4"
lazy_static = "^1.4"
log = "^0.4"
thiserror = "^1"
toml = "^0.5"
tree-sitter = "^0.20"

# Required for tree-sitter
[build-dependencies]
cc="^1.0"

[lib]
crate-type = ["rlib", "dylib"]

[[bin]]
name = "qg"
