on: [push, pull_request, pull_request_target]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: dependencies
        run:  sudo apt install build-essential
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: test
        run: cargo test
